# Board: Generic ESP32-S3 Board (Generic)
# Definition: definitions/boards/generic-esp32s3/manifest.yaml

# Pour configuration générale de Waveshare: https://community.home-assistant.io/t/waveshare-esp32-6ch-relay-board-config-yaml/1007965
# Pour Broan: https://github.com/nspitko/broan_erv_uart

esp32:
  variant: esp32s3
  framework:
    type: esp-idf

logger:
  # level: VERY_VERBOSE
  level: DEBUG

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: Échangeur Fallback Hotspot
    password: !secret ap_password

captive_portal:

external_components:
  - source:
      type: local
      path: /Users/jfhamel/GitRepo/broan_erv_uart/components
    components: [ broan ]

uart:
  id: rs485
  tx_pin: GPIO17
  rx_pin: GPIO18
  baud_rate: 38400
  rx_buffer_size: 2048

  debug:
   direction: BOTH
   dummy_receiver: false
   sequence:
     - lambda: UARTDebug::log_hex(direction, bytes, ' ');

broan:
  uart_id: rs485
  id: mybroan

esphome:
  name: echangeur
  friendly_name: Échangeur
  on_boot:
    priority: 600
    then:
      - select.set:
          id: control_source
          option: "Contrôleur mural"

select:
  - platform: template
    name: "Contrôle de l'échangeur"
    id: control_source
    initial_option: "Contrôleur mural"
    optimistic: true
    options:
      - "Home Assistant"
      - "Contrôleur mural"
    set_action:
      then:
        - lambda: |-
            id(mybroan).setListenOnly(x == "Contrôleur mural");
        - if:
            condition:
              lambda: 'return x == "Contrôleur mural";'
            then:
              - switch.turn_off: relay1
            else:
              - switch.turn_on: relay1

  - platform: broan
    commanded_fan_mode:
      name: "Mode de ventilation"

number:
  - platform: broan

    # Speed as a ratio of min vs max speed. Eg, if your MIN is 20 CFM and your MAX is
    # 40 CFM, 50% means medium rill be at 30 CFM
    fan_speed:
      name: "Vitesse en échange"

    # How many minutes in CONT per hour in inttermitent mode
    intermittent_period:
      name: "Période d'intermittance"

    humidity_setpoint:
      name: "Consigne d'humitité"

    turbo_duration:
      name: "Durée du turbo"

    filter_life_reset_duration:
      name: "Durée de réinitialisation du filtre (mois)"

sensor:
  - platform: wifi_signal
    name: "Signal wifi (dB)"
    update_interval: 60s

  - platform: broan
    power:
      name: "Puissance consommée"

    temperature:
      name: "Température extérieurs"

    filter_life:
      name: "Durée restante du filtre"

    supply_fan_cfm:
      name: "Débit d'entrée (CFM)"

    exhaust_fan_cfm:
      name: "Débit de sortie (CFM)"

    supply_fan_rpm:
      name: "Vitesse du ventilateur d'enbtrée (RPM)"

    exhaust_fan_rpm:
      name: "Vitesse du ventilateur de sortie (RPM)"

    indoor_temperature:
      name: "Tempérarture intérieure"

    indoor_humidity:
      name: "Humidité intérieure"

    override_remaining:
      name: "Temps restant turbo SdB"

    turbo_remaining:
      name: "Temps restant turbo"

  - platform: homeassistant
    id: myhumidity
    name: "Humidité HA"
    # internal: true
    entity_id: sensor.sonoff_snzb_02wd_humidite
    on_value:
      then:
        lambda: id(mybroan).setCurrentHumidity(id(myhumidity).state);

  - platform: homeassistant
    id: mytemperature
    name: "Température HA"
    # internal: true
    entity_id: sensor.sonoff_snzb_02wd_temperature
    on_value:
      then:
        lambda: id(mybroan).setCurrentTemperature(id(mytemperature).state);

button:
  - platform: restart
    name: "Redémarrer"
    id: restart_button
    # internal: true

  - platform: factory_reset
    name: "Remise à zéro d'usine"
    id: reset
    internal: true

  - platform: safe_mode
    name: "Mode sans échec"
    internal: true

  - platform: broan
    # Resets filter life to 7884000 seconds / 3 months (Default behavior)
    filter_life_reset:
      name: "Réinitialisation filtres"

time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: status
    name: "État"

  - platform: gpio
    name: "Bouton de démarrage"
    pin:
      number: 0
      ignore_strapping_warning: true
      mode:
        input: true
      inverted: true
    disabled_by_default: true
    on_press:
      then:
        - button.press: restart_button

text_sensor:
  - platform: version
    name: "Version micrologiciel"

  - platform: wifi_info
    ip_address:
      name: "Adresse IP"
      entity_category: diagnostic
    ssid:
      name: "SSID"
      entity_category: diagnostic
    mac_address:
      name: "Adresse MAC"
      entity_category: diagnostic

  - platform: broan
    base_fan_mode:
      name: "Mode de base"
    ventilation_state:
      name: "Ventilation actuelle"

switch:
  - platform: broan
    humidity_control:
      name: "Contrôle d'hummidité"
      id: humcontrol
      on_turn_on:
        then:
          lambda: id(mybroan).setCurrentHumidity(id(myhumidity).state);
    turbo:
      name: "Turbo"

  - platform: gpio
    pin: GPIO1
    id: relay1
    name: Relay 1
    internal: true

  - platform: gpio
    pin: GPIO2
    id: relay2
    name: Relay 2
    internal: true

  - platform: gpio
    pin: GPIO41
    id: relay3
    name: Relay 3
    internal: true

  - platform: gpio
    pin: GPIO42
    id: relay4
    name: Relay 4
    internal: true

  - platform: gpio
    pin:
      number: GPIO45
      ignore_strapping_warning: true
    id: relay5
    name: Relay 5
    internal: true

  - platform: gpio
    pin:
      number: GPIO46
      ignore_strapping_warning: true
    id: relay6
    internal: true
    name: Relay 6

  - platform: template
    name: Buzzer
    icon: mdi:volume-high
    turn_on_action:
      - rtttl.play:
          id: rtttl_buzzer
          rtttl: 'beep:d=4,o=5,b=100:16e6'
    turn_off_action:
      - rtttl.stop:
          id: rtttl_buzzer
    internal: true

output:
  - platform: ledc
    pin: GPIO21
    id: buzzer_output

rtttl:
  output: buzzer_output
  id: rtttl_buzzer
  gain: 40%

light:
  - platform: esp32_rmt_led_strip
    chipset: ws2812
    pin: GPIO38
    num_leds: 1
    rgb_order: RGB
    name: "RGB LED"
    id: rgb_led
    internal: true
